### ISSUE TITLE
Network support?

### ISSUE THREAD

**Issue by gingerbeardman** [myelin/rpcemu-macos#5]
Is it possible to activate network support?

**Comment by myelin** [comment]
I believe Timothy/VincentVega mentioned that this wasn't implemented, so this is a (big?) todo.

**Comment by gingerbeardman** [comment]
Ah OK. I gave up trying both network workarounds, eg. Tunneling

**Comment by Septercius** [comment]
I did look into it when I was developing my Mac patches, but I never got it to work properly.  There were some discussions (back in November of last year) on the mailing list involving Theo M. and Matthew H. about using another library ("Slirp") for all three platforms (Mac, Linux, Windows).  I think it might have worked on one of Francis Devereux's patches a while ago, but since then, it's been the big missing feature of the Mac port.

**Comment by gingerbeardman** [comment]
0.9.2, released yesterday, includes network support. Are there plans to update?

http://www.marutan.net/rpcemu/

**Comment by gingerbeardman** [comment]
Any word on including the latest upstream changes? Thanks!

**Comment by myelin** [comment]
I'll get around to updating with Timothy's latest patches at some point... sorry for the delay; I have very little time for non-work projects right now!

**Comment by gingerbeardman** [comment]
Solved in 0.9.2 mac-patch-v2

https://homepages.plus.net/pittdj/rpcemu/
